server:
  port: 8888

cloud:
  aws:
    s3:
      bucket: hh-record-project
    region:
      static: ap-northeast-2
    stack:
      auto: false

---
spring:
  profiles:
    active: local, dev, local2
    include:
      - aws
      - google
      - email

---
spring:
  profiles:
    active: dev
    include: rds
