server:
  port: 8888

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000


cloud:
  aws:
    s3:
      bucket: hh-record-project
    region:
      static: ap-northeast-2
    stack:
      auto: false

---
spring:
  profiles:
    active: local, dev, local2
    include:
      - aws
      - google
      - email

---
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://hh-record-project.cemazhv655rv.ap-northeast-2.rds.amazonaws.com:3306/record
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
  profiles:
    active: dev
