###
POST {{host_api}}/auth/google
Content-Type: application/json

{
  "code": "4/0AX4XfWh-MkxxXr226OWVPfxzaAxq_DDBg9SydhSkj2XgtinRq6Z_pmNZXcJDjb2kgURnLw",
  "redirectUri": "http://localhost:8888/login/oauth2/code/google",
  "provider": "GOOGLE"
}