### 회원가입
POST {{host_api}}/hh-record-intro/sign-up
Content-Type: application/json

{
  "id": "admin1",
  "email": "tnswh2023@naver.com",
  "password": "1111",
  "userName": "test",
  "phoneNumber": "ssss"
}

### 로그인
POST {{host_api}}/hh-record-intro/login
Content-Type: application/json

{
  "id": "admin1",
  "password": "1111"
}
> {%
client.global.set('AUTH-TOKEN', response.body.data)
client.log(client.global.get('AUTH-TOKEN'));
 %}

### my-page
GET {{host_api}}/hh-record/my-page/
Content-Type: application/json
AUTH-TOKEN: {{AUTH-TOKEN}}

### my page 수정
PUT {{host_api}}/hh-record/my-page/
Content-Type: application/json
AUTH-TOKEN: {{AUTH-TOKEN}}

{
  "userName": "admin1",
  "phoneNumber": "01011112222",
  "isPrivate": false,
  "profileImgUrl": "https://hh-record-project.s3.ap-northeast-2.amazonaws.com/USER/2022030115434274915f2ce73b4deef1ade05f6ca68c4c6e6fc786fa3a8df532973609de10ea9a054.jpg"
}

### my page 삭제
DELETE {{host_api}}/hh-record/my-page/
Content-Type: application/json
AUTH-TOKEN: {{AUTH-TOKEN}}

### 현재 비밀번호 확인
POST {{host_api}}/hh-record/my-page/password-status
Content-Type: application/json
AUTH-TOKEN: {{AUTH-TOKEN}}

{
  "password": "1111"
}

### 비밀번호 변경
POST {{host_api}}/hh-record/my-page/password
Content-Type: application/json
AUTH-TOKEN: {{AUTH-TOKEN}}

{
  "password" : "1111"
}

### 메일 보내기
POST {{host_api}}/hh-record-intro/user-certification
Content-Type: application/json

{
  "id": "admin1",
  "email": "tnswh2023@naver.com"
}

### 메일 확인
POST {{host_api}}/hh-record-intro/user-certification-check
Content-Type: application/json

{
  "certificationNumber": "05564075"
}

### follow
POST {{host_api}}/hh-record/follow
AUTH-TOKEN: {{AUTH-TOKEN}}
Content-Type: application/json

{
  "memberSeq": 2
}

### unfollow
POST {{host_api}}/hh-record/unfollow
AUTH-TOKEN: {{AUTH-TOKEN}}
Content-Type: application/json

{
  "memberSeq": 2
}