### 일기 리스트
GET {{host_api}}/hh-record/records-main?search=ss&code=s
Content-Type: application/json
AUTH_TOKEN: {{AUTH_TOKEN}}

### 일기 생성
POST {{dev_api}}/hh-record/records
Content-Type: application/json
AUTH_TOKEN: {{AUTH_TOKEN}}

{
  "thumbnailUrl": "sss",
  "title": "title",
  "content": "content",
  "fileKey": "file"
}
